module.exports = {
    purchasedCertificates : [
        {
            number: 54321,
            title: 'One Conventional Oil',
            price: '24.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Cybil Bennett',
            phoneNumber: '801-978-7257',
            status: 'Redeemed',
            nameOfRedemption: 'James Sunderland',
            dateRedeemed: '12/07/2017',
            timeRedeemed: '3:30pm',
            storeRedeemed: '#967'
        },
        {
            number: 54262,
            title: 'One Synthetic Blend/High Milage',
            price: '59.99',
            state: 'Utah',
            city: 'Draper',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Henry Townshed',
            phoneNumber: '801-653-7677',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null
        },
        {
            number: 55674,
            title: 'One Full Synthetic',
            price: '79.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Clawdia Gillespie',
            phoneNumber: '801-274-4213',
            status: 'Redeemed',
            nameOfRedemption: 'Alessa Gillespie',
            dateRedeemed: '01/04/2017',
            timeRedeemed: '1:40pm',
            storeRedeemed: '#969'
        },
        {
            number: 56734,
            title: 'Fuel System Cleaning',
            price: '112.00',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Travis Grady',
            phoneNumber: '801-512-4595',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null
        },
        {
            number: 54755,
            title: 'Headlight Restoration',
            price: '31.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Harry Mason',
            phoneNumber: '801-948-2347',
            status: 'Redeemed',
            nameOfRedemption: 'Cheryl Mason',
            dateRedeemed: '10/20/2015',
            timeRedeemed: '5:25pm',
            storeRedeemed: '#967'
        },
        {
            number: 58653,
            title: 'Tire Rotation',
            price: '19.99',
            state: 'Utah',
            city: 'Murray',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Marry Sunderland',
            phoneNumber: '801-542-5432',
            status: 'Redeemed',
            nameOfRedemption: 'James Sunderland',
            dateRedeemed: '11/14/2016',
            timeRedeemed: '1:20pm',
            storeRedeemed: '#968'
        },
        {
            number: 52345,
            title: 'One Conventional Oil',
            price: '24.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Harry Mason',
            phoneNumber: '801-699-3195',
            status: 'Redeemed',
            nameOfRedemption: 'Joshua Shepherd',
            dateRedeemed: '12/07/2017',
            timeRedeemed: '3:30pm',
            storeRedeemed: '#969'
        },
        {
            number: 54743,
            title: '4-Pack Conventional Oil',
            price: '79.99',
            state: 'Utah',
            city: 'Orem',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Murphy Pendleton',
            phoneNumber: '801-421-5475',
            status: 'Redeemed',
            nameOfRedemption: 'Anne Cunningham',
            dateRedeemed: '12/07/2017',
            timeRedeemed: '3:30pm',
            storeRedeemed: '#967'
        },
        {
            number: 54325,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null
        }
    ]
}