module.exports = {
    purchasedCertificates : [
        {
            number: 54321,
            title: 'One Conventional Oil',
            price: '24.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Cybil Bennett',
            phoneNumber: '801-978-7257',
            datePurchased: '12-06-2017',
            status: 'Redeemed',
            nameOfRedemption: 'James Sunderland',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '967',
            licensePlate: '43DGB4'
        },
        {
            number: 54262,
            title: 'One Synthetic Blend/High Milage',
            price: '59.99',
            state: 'Utah',
            city: 'Draper',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Henry Townshed',
            phoneNumber: '801-653-7677',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 55674,
            title: 'One Full Synthetic',
            price: '79.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Clawdia Gillespie',
            phoneNumber: '801-274-4213',
            datePurchased: '12/06/2017',
            status: 'Redeemed',
            nameOfRedemption: 'Alessa Gillespie',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '969',
            licensePlate: '43DGB4'
        },
        {
            number: 56734,
            title: 'Fuel System Cleaning',
            price: '112.00',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Travis Grady',
            phoneNumber: '801-512-4595',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 54755,
            title: 'Headlight Restoration',
            price: '31.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Harry Mason',
            phoneNumber: '801-948-2347',
            datePurchased: '12/06/2017',
            status: 'Redeemed',
            nameOfRedemption: 'Cheryl Mason',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '967',
            licensePlate: '43DGB4'
        },
        {
            number: 58653,
            title: 'Tire Rotation',
            price: '19.99',
            state: 'Utah',
            city: 'Murray',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Marry Sunderland',
            phoneNumber: '801-542-5432',
            datePurchased: '12/06/2017',
            status: 'Redeemed',
            nameOfRedemption: 'James Sunderland',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '968',
            licensePlate: '43DGB4'
        },
        {
            number: 52345,
            title: 'One Conventional Oil',
            price: '24.99',
            state: 'Utah',
            city: 'Sandy',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Harry Mason',
            phoneNumber: '801-699-3195',
            datePurchased: '12/06/2017',
            status: 'Redeemed',
            nameOfRedemption: 'Joshua Shepherd',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '969',
            licensePlate: '43DGB4'
        },
        {
            number: 54743,
            title: '4-Pack Conventional Oil',
            price: '79.99',
            state: 'Utah',
            city: 'Orem',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Murphy Pendleton',
            phoneNumber: '801-421-5475',
            datePurchased: '12/06/2017',
            status: 'Redeemed',
            nameOfRedemption: 'Anne Cunningham',
            dateRedeemed: new Date('Mon Jan 29 2018 11:13:28 GMT-0700'),
            storeRedeemed: '967',
            licensePlate: '43DGB4'
        },
        {
            number: 54325,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 44213,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 52236,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 56842,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 53267,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        },
        {
            number: 63572,
            title: '4-Pack Full Synthetic',
            price: '303.96',
            state: 'Utah',
            city: 'Midvale',
            email: 'purchaser@email.com',
            nameOfBuyer: 'Eileen Galvin',
            phoneNumber: '801-371-2863',
            datePurchased: '12/06/2017',
            status: 'Redeemable',
            nameOfRedemption: null,
            dateRedeemed: null,
            timeRedeemed: null,
            storeRedeemed: null,
            licensePlate: null
        }
    ]
}